// flow-typed signature: e534c0c9bc5f0923ef6fcdb2ccf45505
// flow-typed version: <<STUB>>/@namics/eslint-config_v^4.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@namics/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@namics/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@namics/eslint-config/configurations/es5-browser-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es5-browser' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es5-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es5-node-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es5-node' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es5' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es6-browser-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es6-browser' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es6-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es6-node-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es6-node' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es6-react-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es6-react' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/es6' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/flow-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/configurations/flow' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/best-practices-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/best-practices' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/errors-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/errors' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/es6-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/es6-disable' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/es6' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/flow-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/flow' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/imports-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/imports' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/node-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/node-disable' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/node' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/react-a11y-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/react-a11y' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/react-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/react' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/strict-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/strict' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/style-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/style' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/variables-disable-styles' {
  declare module.exports: any;
}

declare module '@namics/eslint-config/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module '@namics/eslint-config/configurations/es5-browser-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es5-browser-disable-styles'>;
}
declare module '@namics/eslint-config/configurations/es5-browser.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es5-browser'>;
}
declare module '@namics/eslint-config/configurations/es5-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es5-disable-styles'>;
}
declare module '@namics/eslint-config/configurations/es5-node-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es5-node-disable-styles'>;
}
declare module '@namics/eslint-config/configurations/es5-node.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es5-node'>;
}
declare module '@namics/eslint-config/configurations/es5.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es5'>;
}
declare module '@namics/eslint-config/configurations/es6-browser-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es6-browser-disable-styles'>;
}
declare module '@namics/eslint-config/configurations/es6-browser.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es6-browser'>;
}
declare module '@namics/eslint-config/configurations/es6-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es6-disable-styles'>;
}
declare module '@namics/eslint-config/configurations/es6-node-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es6-node-disable-styles'>;
}
declare module '@namics/eslint-config/configurations/es6-node.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es6-node'>;
}
declare module '@namics/eslint-config/configurations/es6-react-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es6-react-disable-styles'>;
}
declare module '@namics/eslint-config/configurations/es6-react.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es6-react'>;
}
declare module '@namics/eslint-config/configurations/es6.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/es6'>;
}
declare module '@namics/eslint-config/configurations/flow-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/flow-disable-styles'>;
}
declare module '@namics/eslint-config/configurations/flow.js' {
  declare module.exports: $Exports<'@namics/eslint-config/configurations/flow'>;
}
declare module '@namics/eslint-config/rules/best-practices-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/best-practices-disable-styles'>;
}
declare module '@namics/eslint-config/rules/best-practices.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/best-practices'>;
}
declare module '@namics/eslint-config/rules/errors-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/errors-disable-styles'>;
}
declare module '@namics/eslint-config/rules/errors.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/errors'>;
}
declare module '@namics/eslint-config/rules/es6-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/es6-disable-styles'>;
}
declare module '@namics/eslint-config/rules/es6-disable.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/es6-disable'>;
}
declare module '@namics/eslint-config/rules/es6.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/es6'>;
}
declare module '@namics/eslint-config/rules/flow-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/flow-disable-styles'>;
}
declare module '@namics/eslint-config/rules/flow.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/flow'>;
}
declare module '@namics/eslint-config/rules/imports-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/imports-disable-styles'>;
}
declare module '@namics/eslint-config/rules/imports.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/imports'>;
}
declare module '@namics/eslint-config/rules/node-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/node-disable-styles'>;
}
declare module '@namics/eslint-config/rules/node-disable.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/node-disable'>;
}
declare module '@namics/eslint-config/rules/node.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/node'>;
}
declare module '@namics/eslint-config/rules/react-a11y-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/react-a11y-disable-styles'>;
}
declare module '@namics/eslint-config/rules/react-a11y.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/react-a11y'>;
}
declare module '@namics/eslint-config/rules/react-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/react-disable-styles'>;
}
declare module '@namics/eslint-config/rules/react.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/react'>;
}
declare module '@namics/eslint-config/rules/strict-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/strict-disable-styles'>;
}
declare module '@namics/eslint-config/rules/strict.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/strict'>;
}
declare module '@namics/eslint-config/rules/style-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/style-disable-styles'>;
}
declare module '@namics/eslint-config/rules/style.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/style'>;
}
declare module '@namics/eslint-config/rules/variables-disable-styles.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/variables-disable-styles'>;
}
declare module '@namics/eslint-config/rules/variables.js' {
  declare module.exports: $Exports<'@namics/eslint-config/rules/variables'>;
}
