// flow-typed signature: d3c33ac59f0137bbea8fff01efb19ced
// flow-typed version: <<STUB>>/eslint-config_v0.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config/node' {
  declare module.exports: any;
}

declare module 'eslint-config/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config/node.js' {
  declare module.exports: $Exports<'eslint-config/node'>;
}
declare module 'eslint-config/react.js' {
  declare module.exports: $Exports<'eslint-config/react'>;
}
