// flow-typed signature: e0965e951bcbc137c4b6b861e428169f
// flow-typed version: <<STUB>>/camel-case_v3.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camel-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'camel-case' {

  declare export default function camelCase(value: string): string;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'camel-case/camel-case' {
  declare module.exports: any;
}

// Filename aliases
declare module 'camel-case/camel-case.js' {
  declare module.exports: $Exports<'camel-case/camel-case'>;
}
