// flow-typed signature: 7bf5e000bf08317bfe25b8b74e711a1d
// flow-typed version: <<STUB>>/capitalize_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'capitalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'capitalize' {
	declare export function words(value: string): string;
	declare export default function capitalize(value: string): string;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'capitalize/index' {
  declare module.exports: $Exports<'capitalize'>;
}
declare module 'capitalize/index.js' {
  declare module.exports: $Exports<'capitalize'>;
}
