// flow-typed signature: d534579f035f34b67e687a26bb6fcca2
// flow-typed version: <<STUB>>/to-pascal-case_v1.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'to-pascal-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'to-pascal-case' {
  declare export default function toPascalCase(value: string): string;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'to-pascal-case/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'to-pascal-case/index' {
  declare module.exports: $Exports<'to-pascal-case'>;
}
declare module 'to-pascal-case/index.js' {
  declare module.exports: $Exports<'to-pascal-case'>;
}
declare module 'to-pascal-case/test/index.js' {
  declare module.exports: $Exports<'to-pascal-case/test/index'>;
}
